name: Auto Commit on PR Label

on:
  pull_request:
    types: [labeled, opened]
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-commit-on-label:
    uses: rtoora-tranzact/github.workflows/.github/workflows/auto-commit-reusable.yml@main
    # uses: ./.github/workflows/auto-commit-reusable.yml
    with:
      target_branch: ${{ github.base_ref }}
      commit_message_suffix: "AUTOMATED COMMIT"
    secrets:
      PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}