name: Build
on:
  pull_request:
    branches:
      - develop
      - main
  # push:
  #   branches:
  #     - develop
  #     - main
jobs:
  # conventional-commits-linting:
  #   uses: TRANZACT/TzDigital.GitHub.Workflows/.github/workflows/conventional-commit-linting.yml@main

  build-lib:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # if: |
    #   github.event_name == 'pull_request' ||
    #   (github.event_name == 'push' && !contains(github.event.head_commit.message, 'AUTOMATED COMMIT'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore