name: "Check PR labels"
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]
jobs:
  check-labels:
    runs-on: ubuntu-latest
    env:
      LABELS_NONE_OF: invalid,wontfix,duplicate,question
      LABELS_ANY_OF: documentation,enhancement,bug,maintenance,dependencies,post-release
    steps:
      - uses: TRANZACT/label-checker@v1.0.1
        with:
          none_of: ${{ env.LABELS_NONE_OF }}
          any_of: ${{ env.LABELS_ANY_OF }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - id: comment-errors
        if: ${{ failure() }}
        name: Comment Label Errors
        uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const errors = context.payload.label_checker.errors;
                if (errors.length > 0) {
                const errorMessage = `The following labels are required: ${errors.join(', ')}`;
                await github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: errorMessage
                });
                }